# Generated by Django 3.2.7 on 2021-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
